"""changed duration to a string not float

Revision ID: 052f97d13ab7
Revises: 22d5f6c3abb7
Create Date: 2018-06-18 11:33:35.468400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052f97d13ab7'
down_revision = '22d5f6c3abb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'ingred')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('ingred', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
