"""added duration/strength to recipes

Revision ID: 22d5f6c3abb7
Revises: 4f0a6dfaf15d
Create Date: 2018-06-17 21:25:35.288059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d5f6c3abb7'
down_revision = '4f0a6dfaf15d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('duration', sa.Float(), nullable=True))
    op.add_column('recipes', sa.Column('strength', sa.Integer(), nullable=True))
    op.drop_column('recipes', 'ingred')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('ingred', sa.INTEGER(), nullable=True))
    op.drop_column('recipes', 'strength')
    op.drop_column('recipes', 'duration')
    # ### end Alembic commands ###
