"""added new connections and missing sell/hearts on route

Revision ID: 4f0a6dfaf15d
Revises: f69838c5b9e6
Create Date: 2018-06-15 00:06:57.363903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f0a6dfaf15d'
down_revision = 'f69838c5b9e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'ingred')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('ingred', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
