"""parent child think this works

Revision ID: da48be256465
Revises: e1c6571af7ad
Create Date: 2018-06-10 12:37:29.233026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da48be256465'
down_revision = 'e1c6571af7ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'ingred')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('ingred', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
