"""trying to add recipes join table

Revision ID: e1c6571af7ad
Revises: 959a6502dece
Create Date: 2018-06-10 10:30:25.484408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c6571af7ad'
down_revision = '959a6502dece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_name', sa.String(length=120), nullable=True),
    sa.Column('recipe_type', sa.String(length=30), nullable=True),
    sa.Column('recipe_info', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_recipe_info'), 'recipes', ['recipe_info'], unique=False)
    op.create_index(op.f('ix_recipes_recipe_name'), 'recipes', ['recipe_name'], unique=True)
    op.create_index(op.f('ix_recipes_recipe_type'), 'recipes', ['recipe_type'], unique=False)
    op.create_table('recipes_ingreds',
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('ingred_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingred_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes_ingreds')
    op.drop_index(op.f('ix_recipes_recipe_type'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_recipe_name'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_recipe_info'), table_name='recipes')
    op.drop_table('recipes')
    # ### end Alembic commands ###
